### ISSUE TITLE
Any news on this?

### ISSUE THREAD

**Issue by h-2** [MikaelUrankar/signal-desktop#1]
Having signal-desktop would make my life soo much easier!

Have you tried creating an issue for this port in the FreeBSD bug tracker? Maybe others can help resolve the last issues...

Thank you for working on this!

**Comment by MikaelUrankar** [comment]
Sadly no news on this PR. Working with electron and npm is really hard and demotivating. The issue with electron (the ENOTTY problem) is still not solved...

**Comment by MikaelUrankar** [comment]
In case you're still interested, I've made some progress, it builds and seems to work fine.

**Comment by h-2** [comment]
If there is a port that I could test, I would gladly give it a try!

**Comment by MikaelUrankar** [comment]
I've attached a pkg here: https://github.com/MikaelUrankar/signal-desktop/releases/tag/5.33.0
It was built against 12.3 but works on my 14-Current system. You'll have to manually install missing dependencies.

**Comment by h-2** [comment]
Awesome, thanks for your work on this! I will give it a try, as soon as I am home at my FreeBSD Desktop.

**Comment by h-2** [comment]
Just tried it. Installs fine, finds people and groups, transmits messages, everything looking very good 👌🏻 

Will be testing it more thoroughly the next days, but already: thanks a lot!

**Comment by abelbabel** [comment]
Tried it on FreeBSD 12.3-RELEASE-p1 ... works fine so far! Thank you very much! It was about time (not your fault, obviously).

**Comment by h-2** [comment]
Just wanted to say that I haven't encountered any problems so far! Would be great to have this as an official port.

**Comment by MikaelUrankar** [comment]
I need to convince tagattie@ to update electron to v17 and push it into the ports tree. I'll then be able to push signal-desktop into the ports tree.

**Comment by duckinator** [comment]
FYI: Signal-Desktop v5.42.0 switched to Electron v18: https://github.com/signalapp/Signal-Desktop/commits/v5.42.0/package.json

**Comment by duckinator** [comment]
Looks like tagattie added Electron v18 to their repo, too, though: https://github.com/tagattie/FreeBSD-Electron/commit/d5d9f96405fc6e2254f42f7d04e144a16c20d63d

**Comment by MikaelUrankar** [comment]
I've committed net-im/signal-desktop in the ports tree.

**Comment by duckinator** [comment]
@MikaelUrankar when I try building it, it fails to fetch `sqlcipher.tar.gz`. I also get a 404 for it (on all the servers it tried) in Firefox. Do you by chance know what would cause this?

```
root@cerberus:/usr/ports/net-im/signal-desktop # make install
/!\ WARNING /!\

You have security/openssl installed but do not have
DEFAULT_VERSIONS+=ssl=openssl set in your make.conf

===>  License AGPLv3 accepted by the user
===>   signal-desktop-5.46.0 depends on file: /usr/local/sbin/pkg - found
=> sqlcipher.tar.gz doesn't seem to exist in /usr/ports/distfiles/.
=> Attempting to fetch http://distcache.FreeBSD.org/local-distfiles/mikael/signal-desktop/sqlcipher.tar.gz
fetch: http://distcache.FreeBSD.org/local-distfiles/mikael/signal-desktop/sqlcipher.tar.gz: Not Found
=> Attempting to fetch http://distcache.us-east.FreeBSD.org/local-distfiles/mikael/signal-desktop/sqlcipher.tar.gz
fetch: http://distcache.us-east.FreeBSD.org/local-distfiles/mikael/signal-desktop/sqlcipher.tar.gz: Not Found
=> Attempting to fetch http://distcache.eu.FreeBSD.org/local-distfiles/mikael/signal-desktop/sqlcipher.tar.gz
fetch: http://distcache.eu.FreeBSD.org/local-distfiles/mikael/signal-desktop/sqlcipher.tar.gz: Not Found
=> Attempting to fetch http://distcache.us-west.FreeBSD.org/local-distfiles/mikael/signal-desktop/sqlcipher.tar.gz
fetch: http://distcache.us-west.FreeBSD.org/local-distfiles/mikael/signal-desktop/sqlcipher.tar.gz: No route to host
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/sqlcipher.tar.gz
fetch: http://distcache.FreeBSD.org/ports-distfiles/sqlcipher.tar.gz: Not Found
=> Couldn't fetch it - please try to retrieve this
=> port manually into /usr/ports/distfiles/ and try again.
*** Error code 1

Stop.
make: stopped in /usr/ports/net-im/signal-desktop
root@cerberus:/usr/ports/net-im/signal-desktop #
```

**Comment by duckinator** [comment]
Talked to someone on the FreeBSD Discord and the answer seems to be to just give the servers some time.

**Comment by MikaelUrankar** [comment]
sqlcipher was definetely missing, I've just uploaded it and should be available in a couple of hours. Thanks for the report.
