### ISSUE TITLE
Couldn't fetch it packages

### ISSUE THREAD

**Issue by Martinfx** [MikaelUrankar/signal-desktop#2]
===>  License AGPLv3 accepted by the user
===>   signal-desktop-5.32.0 depends on file: /usr/local/sbin/pkg - found
=> signal-desktop-5.32.0-npm-cache.tar.gz doesn't seem to exist in /usr/ports/distfiles/.
=> Attempting to fetch https://cocyte.westeurope.cloudapp.azure.com/signal-desktop/signal-desktop-5.32.0-npm-cache.tar.gz
fetch: https://cocyte.westeurope.cloudapp.azure.com/signal-desktop/signal-desktop-5.32.0-npm-cache.tar.gz: No address record
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/signal-desktop-5.32.0-npm-cache.tar.gz
fetch: http://distcache.FreeBSD.org/ports-distfiles/signal-desktop-5.32.0-npm-cache.tar.gz: Not Found
=> Couldn't fetch it - please try to retrieve this
=> port manually into /usr/ports/distfiles/ and try again.
*** Error code 1

**Comment by MikaelUrankar** [comment]
Can you try the 5.33.0 branch?

**Comment by Martinfx** [comment]
> Can you try the 5.33.0 branch?

You have bad USE_XORG they cannot found this module jpeg gettext-runtime.
Branch 5.33 has same problem 
```
sudo make
/!\ signal-desktop-5.32.0: Makefile warnings, please consider fixing /!\

Using USE_XORG alone is deprecated, please use USES=xorg

Using USE_GNOME alone is deprecated, please add USES=gnome.

Using USE_GL alone is deprecated, please add USES=gl.

You are using USE_GITHUB and WRKSRC is set which is wrong.  Set GH_PROJECT
correctly or set WRKSRC_SUBDIR and remove WRKSRC entirely.

Not validating first entry in CATEGORIES due to being outside of PORTSDIR.
Please ensure this is proper when committing.

===>  License AGPLv3 accepted by the user
===>   signal-desktop-5.32.0 depends on file: /usr/local/sbin/pkg - found
=> signal-desktop-5.32.0-npm-cache.tar.gz doesn't seem to exist in /usr/ports/distfiles/.
=> Attempting to fetch https://cocyte.westeurope.cloudapp.azure.com/signal-desktop/signal-desktop-5.32.0-npm-cache.tar.gz
fetch: https://cocyte.westeurope.cloudapp.azure.com/signal-desktop/signal-desktop-5.32.0-npm-cache.tar.gz: size mismatch: expected 3509322, actual 3087360
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/signal-desktop-5.32.0-npm-cache.tar.gz
fetch: http://distcache.FreeBSD.org/ports-distfiles/signal-desktop-5.32.0-npm-cache.tar.gz: Not Found
=> Couldn't fetch it - please try to retrieve this
=> port manually into /usr/ports/distfiles/ and try again.
*** Error code 1
```

**Comment by MikaelUrankar** [comment]
should be fixed with https://github.com/MikaelUrankar/signal-desktop/commit/2f088add7716c9d53712c000e7872b3eea52eb41

**Comment by Martinfx** [comment]
Now is without problem
